CREATE TABLE d_season_records (
  school_id INTEGER UNSIGNED NOT NULL,
  season INTEGER UNSIGNED NOT NULL,
  wins INTEGER UNSIGNED NOT NULL,
  losses INTEGER UNSIGNED NOT NULL,
  ties INTEGER UNSIGNED NOT NULL,
  points_for INTEGER UNSIGNED NOT NULL,
  points_against INTEGER UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE d_head_to_head_streaks (
  school_id INTEGER UNSIGNED NOT NULL,
  opp_school_id INTEGER UNSIGNED NOT NULL,
  is_win TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  streak INTEGER UNSIGNED NOT NULL,
  start_season INTEGER UNSIGNED NOT NULL,
  end_season INTEGER UNSIGNED NOT NULL,
  points_for INTEGER UNSIGNED NOT NULL,
  points_against INTEGER UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE d_game_streaks (
  school_id INTEGER UNSIGNED NOT NULL,
  is_win TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  streak INTEGER UNSIGNED NOT NULL,
  start_season INTEGER UNSIGNED NOT NULL,
  end_season INTEGER UNSIGNED NOT NULL,
  points_for INTEGER UNSIGNED NOT NULL,
  points_against INTEGER UNSIGNED NOT NULL
) ENGINE = InnoDB;
